"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const config_1 = require("./config");
exports.app = express();
exports.default = exports.app;
require("./server/module-debug");
require("./server/module-config");
require("./server/dev/module-init_pages");
require("./server/dev/module-refresh");
require("./server/pages/module-default_page");
require("./server/pages/module-pages");
require("./server/pages/module-error_404");
require("./server/services/module-login_logout");
require("./server/services/module-is_admin");
exports.app.listen(config_1.default.port, () => console.log('Listening on port ' + config_1.default.port + '!'));
